name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.PRIVATE_REPO_PAT }}@github.com/naba-network/".insteadOf "ssh://git@github.com/naba-network/"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
